import img from "@/assets/images/man.png";
export interface Provider {
  sl: number;
  providerName: string;
  rating: number;
  avatar?: string;
  contactPhone: string;
  contactEmail: string;
  totalBookings: number;
  isAvailable: boolean;
  status: "Basic" | "Unlimited";
}
export const providers: Provider[] = [
  {
    sl: 1,
    providerName: "John Doe",
    rating: 4.5,
    avatar: img,
    contactPhone: "+880123456789",
    contactEmail: "john@example.com",
    totalBookings: 120,
    isAvailable: true,
    status: "Unlimited",
  },
  {
    sl: 2,
    providerName: "Jane Smith",
    rating: 4.2,
    avatar: img,
    contactPhone: "+880987654321",
    contactEmail: "jane@example.com",
    totalBookings: 95,
    isAvailable: false,
    status: "Basic",
  },
  {
    sl: 3,
    providerName: "Mike Johnson",
    rating: 4.8,
    avatar: img,
    contactPhone: "+880112233445",
    contactEmail: "mike@example.com",
    totalBookings: 150,
    isAvailable: true,
    status: "Unlimited",
  },
  {
    sl: 4,
    providerName: "Emily Davis",
    rating: 4.1,
    avatar: img,
    contactPhone: "+880556677889",
    contactEmail: "emily@example.com",
    totalBookings: 80,
    isAvailable: true,
    status: "Basic",
  },
  {
    sl: 5,
    providerName: "Robert Brown",
    rating: 3.9,
    avatar: img,
    contactPhone: "+880667788990",
    contactEmail: "robert@example.com",
    totalBookings: 60,
    isAvailable: false,
    status: "Basic",
  },
  {
    sl: 6,
    providerName: "Linda Wilson",
    rating: 4.6,
    avatar: img,
    contactPhone: "+880223344556",
    contactEmail: "linda@example.com",
    totalBookings: 110,
    isAvailable: true,
    status: "Unlimited",
  },
  {
    sl: 7,
    providerName: "David Miller",
    rating: 4.3,
    avatar: img,
    contactPhone: "+880334455667",
    contactEmail: "david@example.com",
    totalBookings: 90,
    isAvailable: false,
    status: "Basic",
  },
  {
    sl: 8,
    providerName: "Sarah Taylor",
    rating: 4.7,
    avatar: img,
    contactPhone: "+880445566778",
    contactEmail: "sarah@example.com",
    totalBookings: 130,
    isAvailable: true,
    status: "Unlimited",
  },
  {
    sl: 9,
    providerName: "Chris Anderson",
    rating: 4.0,
    avatar: img,
    contactPhone: "+880556677889",
    contactEmail: "chris@example.com",
    totalBookings: 70,
    isAvailable: false,
    status: "Basic",
  },
  {
    sl: 10,
    providerName: "Patricia Thomas",
    rating: 4.9,
    avatar: img,
    contactPhone: "+880667788990",
    contactEmail: "patricia@example.com",
    totalBookings: 160,
    isAvailable: true,
    status: "Unlimited",
  },
  {
    sl: 11,
    providerName: "Mark Lee",
    rating: 3.8,
    avatar: img,
    contactPhone: "+880778899001",
    contactEmail: "mark@example.com",
    totalBookings: 55,
    isAvailable: false,
    status: "Basic",
  },
  {
    sl: 12,
    providerName: "Nancy Harris",
    rating: 4.4,
    avatar: img,
    contactPhone: "+880889900112",
    contactEmail: "nancy@example.com",
    totalBookings: 100,
    isAvailable: true,
    status: "Unlimited",
  },
  {
    sl: 13,
    providerName: "Steven Clark",
    rating: 4.2,
    avatar: img,
    contactPhone: "+880990011223",
    contactEmail: "steven@example.com",
    totalBookings: 85,
    isAvailable: true,
    status: "Basic",
  },
  {
    sl: 14,
    providerName: "Laura Lewis",
    rating: 4.5,
    avatar: img,
    contactPhone: "+880101112131",
    contactEmail: "laura@example.com",
    totalBookings: 120,
    isAvailable: true,
    status: "Unlimited",
  },
  {
    sl: 15,
    providerName: "Kevin Walker",
    rating: 4.1,
    avatar: img,
    contactPhone: "+880121314151",
    contactEmail: "kevin@example.com",
    totalBookings: 75,
    isAvailable: false,
    status: "Basic",
  },
];
